apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: receiveDiagnosticCreated
  description: Service receiveDiagnosticCreated
spec:
  type: asyncapi
  lifecycle: production
  owner: poc-tesi25
  definition:
    $yaml: https://raw.githubusercontent.com/medmo/backstage-templates/refs/heads/main/ft-catalog-generated/asyncapi-Diagnostic-service.yaml
